import streamlit as st

st.subheader("RETROALIMENTACIÓN")
nombre = st.text_input("Digite su nombre:")
st.markdown(f"su nombre es: {nombre}")

st.caption("**1. ¿Qué es una asíntota?**")
nombre = st.text_input("Digite su respuesta:")
st.markdown(f"respuesta: {nombre}")
st.caption("**2. ¿Cuáles son los tipos principales de asíntotas**")
nombre = st.text_input("La respuesta indicada es:")
st.markdown(f"respuesta: {nombre}")
st.caption("**3. ¿Cómo se define una asíntota horizontal?**")
nombre = st.text_input("La solución es:")
st.markdown(f"respuesta: {nombre}")
st.caption("**4. ¿Qué es una asíntota vertical y cómo se encuentra?**")
nombre = st.text_input("La información que solicita es:")
st.markdown(f"respuesta: {nombre}")
st.caption("**5. ¿Cómo se determina si una función tiene una asíntota horizontal?**")
nombre = st.text_input("El dato solicitado es:")
st.markdown(f"respuesta: {nombre}")
st.caption("**6. ¿Qué diferencia hay entre una asíntota horizontal y una vertical?**")
nombre = st.text_input("la respuesta es:")
st.markdown(f"respuesta: {nombre}")
st.caption("**7. ¿Una función puede tener más de una asíntota horizontal?**")
nombre = st.text_input("digite la información:")
st.markdown(f"respuesta: {nombre}")
st.caption("**8. ¿Cómo se identifican las asíntotas de una función en su gráfica?**")
nombre = st.text_input("Digita la información solicitda:")
st.markdown(f"respuesta: {nombre}")
st.caption("**9. ¿Una asíntota siempre se toca?**")
nombre = st.text_input("¿cual es tu respuesta?:")
st.markdown(f"respuesta: {nombre}")
st.caption("**10. ¿Qué es una asintota horizontal?**")
nombre = st.text_input("¿que vas a responder?:")
st.markdown(f"respuesta: {nombre}")

rango = st.slider("¿que puntución le das a mi página?:", min_value=0, max_value=100)
st.markdown(f"el valor que ingresó es: {rango}")
